### ISSUE TITLE
CDS-44: Remove Obsolete Collection implementations, alias as deprecated to new ones

### ISSUE THREAD

**Issue by LoghinVladDev** [LoghinVladDev/CDS#99]
- [x] UnorderedSet to HashSet -> #89 Required as Prerequisite - 75b577c
- [x] OrderedSet to TreeSet -> #44 Required as Prerequisite
- [x] ListSet to Set -> #89 Required as Prerequisite, Also removal of Unordered / Ordered Set Required
